### PR TITLE
Fix Emoji keyboard in certain cases

### LINKED ISSUE #328: Weird behaviour in landscape when flagNoExtractUi is not set
- Version of the library: 748c208
- Affected devices: All
- Affected versions: All

When opening the emoji keyboard in landscape, the emoji picker is shown on it's own, without the `EditText`. I reproduced that on a default API 28 emulator.
Setting `android:imeOptions="flagNoExtractUi"` works around like before. 

@mario I think that is related to your change?

### PR DESCRIPTION
**Pull request by mario**
This fixes an issue brought to my attention in #328 and a few other issues I've noticed with the Popup view.

### CODE REVIEW

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 1]
```diff
@@ -172,18 +174,22 @@ public void toggle() {
 
       if (isKeyboardOpen) {
         // If the keyboard is visible, simply show the emoji popup.
-        showAtBottom();
+        editText.postDelayed(new Runnable() {
+          @Override public void run() {
+            showAtBottom();
+          }
+        }, 50);
```
[the remark this answers is not in the document]
Comment (mario) [reply emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: Because in rare cases, due to race conditions, we get a smaller height from the keyboard than expected (because it's not fully shown), so the emoji popvuiew is smaller than needed.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 2]
```diff
@@ -212,13 +219,21 @@ void showAtBottom() {
     popupWindow.showAtLocation(rootView, Gravity.NO_GRAVITY, desiredLocation.x, desiredLocation.y);
 
     if (onEmojiPopupShownListener != null) {
+      if (shouldOverrideRegularCondition(context, editText)) {
+        final InputMethodManager inputMethodManager = (InputMethodManager) context.getSystemService(Context.INPUT_METHOD_SERVICE);
+        inputMethodManager.showSoftInput(editText, 0);
```
[the remark this answers is not in the document]
Comment (mario) [reply emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: Because the keyboard won't open in landscape mode if you don't have NoExtractUI flag set, so we have to do it this way.

**Comment by mario** [comment]
I'll investigate the sizing when NOT using adjustResize.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (rubengees) [reply emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: Did it before the other PR of yours?

**Comment by mario** [comment]
Can you let me know the combination you use for activity + edittext (imeOptions) so I can try to debug as I can't really reproduce?

**Comment by mario** [comment]
@rubengees when you get the time to answer, I'll take a look. Got another PR in the mean time :)

**Comment by rubengees** [comment]
On my `Activity` I have no special properties (so no `adjustResize`), the `EmojiEditText` is like this (simplified):

```xml
<com.vanniktech.emoji.EmojiEditText
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:inputType="textMultiLine|textCapSentences|textAutoCorrect"
    android:maxLines="5"
    android:scrollbars="vertical" />
```

**Comment by mario** [comment]
I now came up with a significantly better solution and have rebased the PR against master. Please test and reply accordingly - thanks!

**Comment by vanniktech** [comment]
I'll test it out on Monday. Are there any further changes you want to see for 0.6.0?

**Comment by vanniktech** [comment]
Nah. Just GitHub. Maybe Ruben can help with the Emojis. Also what should we do about EmojiOne?

**Comment by mario** [comment]
I'd drop it if that's what the folks prefer.

**Comment by vanniktech** [comment]
Can we then also update the Emoji ordering @rubengees? I feel like when cutting a new release we should have all of the emojis in place.

**Comment by rubengees** [comment]
Regarding this PR - still does not work in landscape for me. The popup is not shown at all...

> Maybe Ruben can help with the [ignored] Emojis.

I'll try to look into that 🙂 

> Can we then also update the Emoji ordering?

You mean the order in which the emojis are shown in the picker? If yes, I can't think of a way. The generator simply uses the ordering of our datasource.

**Comment by mario** [comment]
@rubengees can you talk the Sample app shipped in the repo (and this PR, in particular) to exhibit the behaviour you mentioned so I can properly debug? I've tried a few combinations and they all work as expected for me :(

**Comment by rubengees** [comment]
@mario Hmm it seems to have been an issue with my app, at least partially. I hide and show the input based on data that is loaded and also instantiated the popup only when it was first used (using Kotlin's `lazy`) and that seemed to have put the logic into an awkward state.

It works mostly now. But I have noticed this:




The first screenshot shows the landscape view without the picker opened. The second with it opened. As you can see, the "done" button is not accessible for the user anymore. I think the popup should only have the height of the keyboard in landscape also.

**Comment by mario** [comment]
So the suggestion is to instantiate the popup as soon as possible due to global layout listener in general. Let me investigate your issue now :)

**Comment by mario** [comment]
Nop, can't reproduce - can you send me a sample layout file? I just remove all the adjustResize and set the flagNoExtractUI and it works as expected :(

**Comment by rubengees** [comment]
I am currently on mobile only, but will try to put something together and investigate more thoroughly asap. My observations above were only quick findings.

**Comment by mario** [comment]
Thanks!

**Comment by mario** [comment]
Sorry to bother, but any progress on getting me a way to reproduce or a fix @rubengees?

**Comment by rubengees** [comment]
Sorry, not yet. I'm currently busy with work, but have not forgotten about it!

**Comment by rubengees** [comment]
I have investigated further and the problems with the popup not showing were all linked to problems with my app, sorry for the confusion... Maybe we should add a disclaimer to the README, that the popup needs to be instantiated as early as possible, to avoid others to make the same mistake? 

Apart from that, only the problem with the popup being above the "done" button is left for me. I can reproduce that without any modifications to the sample or the library. I happens on my real phone (OnePlus 5T, Android 9.0 stock) and also on an default Android Studio emulator (Pixel 2, Android 9.0)

**Comment by mario** [comment]
> I have investigated further and the problems with the popup not showing were all linked to problems with my app, sorry for the confusion... Maybe we should add a disclaimer to the README, that the popup needs to be instantiated as early as possible, to avoid others to make the same mistake?
> 
> Apart from that, only the problem with the popup being above the "done" button is left for me. I can reproduce that without any modifications to the sample or the library. It happens on my real phone (OnePlus 5T, Android 9.0 stock) and also on an default Android Studio emulator (Pixel 2, Android 9.0).

Well, definitely good news! As for the second thing - would you mind telling me where in the sample (either in master or this PR) do you see the "Done" button? :-/ I must be missing something.

**Comment by rubengees** [comment]
@mario Here:




In the first screenshot, you can see the "send" button (in my app, it's a "done" button, but that doesn't make a difference). In the second screenshot, it cannot be accessed, due to the popup being over it.

**Comment by mario** [comment]
Thanks. Will try that emulator then.

**Comment by mario** [comment]
Took me forever to figure this one out, but I guess this is why there are no solutions to this available so far :(

Please test it.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 3]
```diff
@@ -97,9 +97,14 @@ private void updateKeyboardState() {
...
 
     final int availableHeight = rootView.getHeight() - viewInset - (!Utils.isFullScreen(context) ? rect.top : 0);
-    final int keyboardHeight = Utils.shouldOverrideRegularCondition(context, editText) ?
-        Utils.getScreenHeight(context) - editText.getBottom() - (!Utils.isFullScreen(context) ? rect.top : 0)
-        : availableHeight - (rect.bottom - rect.top);
+
+    int keyboardHeight;
+
+    if (Utils.shouldOverrideRegularCondition(context, editText)) {
+      keyboardHeight = (int) ((availableHeight - editText.getBottom() - (0.252 * availableHeight)) + (!Utils.isFullScreen(context) ? availableHeight * 0.055 : 0));
```
Comment (rubengees) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: Can you explain what is going on here?

**Comment by mario** [comment]
Absolutely, if you can test and confirm it works while I rebase? :)

**Comment by mario** [comment]
By how much? Can you screenshot for me?

**Comment by mario** [comment]
Simplified the code and fixed #340 along the way. One more bug remains with landscape orientation that I'm trying to hunt down.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java (hunk 3 above)
Comment (mario) [reply emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: It is a magic calculation based off of some fractions I've found in the Android source code. Not SUPER reliable, but it seemed to work on all the phones I've had. Can you show me a screenshot on how it looks like on yours?

**Comment by mario** [comment]
I *finally* got it. I've opted to show emoji keyboard in a regular view instead of a full screen view because that's how a few other IM apps do it, but it's absolutely the same size as the regular keyboard you use.

Please test, merge, and let's do a release!

File: app/src/main/java/com/vanniktech/emoji/sample/MainActivity.java [hunk 4]
```diff
@@ -114,11 +114,7 @@
   }
 
   @Override public void onBackPressed() {
-    if (emojiPopup != null && emojiPopup.isShowing()) {
-      emojiPopup.dismiss();
-    } else {
-      super.onBackPressed();
-    }
+    super.onBackPressed();
```
Comment (vanniktech) [inline app/src/main/java/com/vanniktech/emoji/sample/MainActivity.java]: If we don't do anything here any longer then we can remove the method completely.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 5]
```diff
@@ -55,57 +59,48 @@
   @Nullable OnEmojiClickListener onEmojiClickListener;
   @Nullable OnEmojiPopupDismissListener onEmojiPopupDismissListener;
 
-  int correctionFactor;
+  int originalIMEOptions = -1;
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]:
```suggestion
  int originalImeOptions = -1;
```

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 6]
```diff
@@ -55,57 +59,48 @@
...
+      updateKeyboardState();
+    }
+  };
 
-      final boolean shouldOverrideRegularCondition = Utils.shouldOverrideRegularCondition(context, editText);
+  private void updateKeyboardState() {
 
-      if (heightDifference > Utils.dpToPx(context, MIN_KEYBOARD_HEIGHT) || shouldOverrideRegularCondition) {
-        correctionFactor = rect.top;
+    int keyboardHeight = Utils.getInputMethodHeight(context);
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]:
```suggestion
    final int keyboardHeight = Utils.getInputMethodHeight(context);
```

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 7]
```diff
@@ -55,57 +59,48 @@
...
 
-        if (shouldOverrideRegularCondition) {
-          height = (int) (Utils.getScreenHeight(context) / 2f - heightDifference * HEIGHT_DIFFERENCE_FACTOR);
-          popupWindow.setHeight(height);
-        } else {
-          height = heightDifference + correctionFactor;
-          popupWindow.setHeight(height);
-        }
-        popupWindow.setWidth(rect.right);
+      Rect rect = Utils.windowVisibleDisplayFrame(context);
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]:
```suggestion
      final Rect rect = Utils.windowVisibleDisplayFrame(context);
```

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 8]
```diff
@@ -156,7 +151,8 @@
 
     popupWindow.setContentView(emojiView);
     popupWindow.setInputMethodMode(PopupWindow.INPUT_METHOD_NOT_NEEDED);
-    popupWindow.setBackgroundDrawable(new BitmapDrawable(context.getResources(), (Bitmap) null)); // To avoid borders and overdraw.
+    popupWindow.setBackgroundDrawable(
+        new BitmapDrawable(context.getResources(), (Bitmap) null)); // To avoid borders and overdraw.
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: nit: Can you revert this?

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 9]
```diff
@@ -176,35 +170,43 @@
...
-    // Manually dispatch the event. In some cases this does not work out of the box reliably.
-    context.getWindow().getDecorView().getViewTreeObserver().dispatchOnGlobalLayout();
+    if (Utils.shouldOverrideRegularCondition(context, editText)) {
+      editText.setImeOptions(editText.getImeOptions() | EditorInfo.IME_FLAG_NO_EXTRACT_UI);
+      inputMethodManager.restartInput(editText);
+    }
+
+    inputMethodManager.showSoftInput(editText, InputMethodManager.RESULT_UNCHANGED_SHOWN,
+        new ResultReceiver(null) {
+          @Override
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: nit: should be on it's own line

File: emoji/src/main/java/com/vanniktech/emoji/Utils.java [hunk 10]
```diff
@@ -50,19 +51,37 @@
...
-    return dpToPx(context, context.getResources().getConfiguration().screenHeightDp);
+  static int getInputMethodHeight(Context context) {
+    try {
+      InputMethodManager imm =
+          (InputMethodManager) context.getApplicationContext().getSystemService(Context.INPUT_METHOD_SERVICE);
+      Class clazz = imm.getClass();
+      Method method = clazz.getDeclaredMethod("getInputMethodWindowVisibleHeight");
+      method.setAccessible(true);
+      return (int) (Integer) method.invoke(imm);
+    } catch (Exception e) {
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/Utils.java]: Can we please log this?

**Comment by mario** [comment]
All done.

**Comment by mario** [comment]
All done!

**Comment by mario** [comment]
This PR fixes #328 and #340.

**Comment by rubengees** [comment]
Sorry for coming back so late! Just tried the latest changes and they seem to not work at all :/ Nothing happens for me when I click on the emoji button in the sample (real device Oneplus 5T, SwiftKey keyboard)...

I also get memory leaks related to the `ResultReceiver`.

**Comment by mario** [comment]
@rubengees can you check what does Utils.getInputMethodHeight returns for you? In the mean time I'll take a look at the receiver.

**Comment by mario** [comment]
Receiver leak should now be fixed.

**Comment by mario** [comment]
You keep disappearing :P I found the method I call via reflection doesn't exist everywhere. Trying to workaround now.

**Comment by rubengees** [comment]
> Can you check what does Utils.getInputMethodHeight returns for you?

590.

Some logic in `updateKeyboardState` seems to be off, directly after opening, the `OnGlobalLayoutListener` seems to be called again and leads to `dismiss` being called.

**Comment by mario** [comment]
@rubengees pushed a fix + fallback.

**Comment by rubengees** [comment]
Works perfectly now!

**Comment by mario** [comment]
Great!

**Comment by mario** [comment]
Would you mind investigating the leak as I have a really awful headache atm?

I would guess its just a matter of setting it to null at the right place.

Formatting wise I think I fixed all the complaints.

**Comment by mario** [comment]
Fixed the leak. There's another that I'm pretty sure is related to Android SDK, but yea... should be all nice now.

**Comment by mario** [comment]
@vanniktech let me know if I need to do anything else to get this merged so we could have a release out in the next few days.

**Comment by vanniktech** [comment]
@rubengees approval and a green CI build ;)

**Comment by rubengees** [comment]
@mario I can't really follow the flow in the `EmojiPopup` anymore code wise, but it works great! I also tried it in a real applications and same results there.

But I still get the leak with the `ResultReceiver` :/

Leak

**Comment by mario** [comment]
@vanniktech and @rubengees - could you point me to the places that need fixing for the build to go green? I seem to miss this somehow :-/

I'll take a look once again at the ResultReceiver, but my suspicion is this is related to Android SDK itself.

@rubengees happy to explain any parts of the code - sorry if it doesn't make sense, the keyboard handling is one of the worst parts of the Android SDK - EVER!

**Comment by rubengees** [comment]
> Could you point me to the places that need fixing for the build to go green?

I usually run `./gradlew build` locally until it reports success. That is basically what CI does also. But good news: I pushed a commit that fixes the remaining style issues.

> I'll take a look once again at the ResultReceiver, but my suspicion is this is related to Android SDK itself.

Had a quick look at it, it seems to be not. It is not a static class and internally uses the `context` of the outer class. That is a leak, since the `context` can't be garbage collected.
I guess you are better able to fix this though, since you know the code better.

> Happy to explain any parts of the code

I would really like a high level explanation of how the code flow is from tapping the emoji button to showing the keyboard. Not required for merging of course, but would like to understand :)

> The keyboard handling is one of the worst parts of the Android SDK - EVER!

I wholeheartedly agree!

File: emoji/src/main/java/com/vanniktech/emoji/Utils.java [hunk 11]
```diff
@@ -71,29 +61,33 @@ static boolean shouldOverrideRegularCondition(@NonNull final Activity context, f
     return false;
   }
 
-  static int getInputMethodHeight(final Context context, final View rootView) {
+  @SuppressWarnings({"unchecked", "JavaReflectionMemberAccess"}) static int getInputMethodHeight(final Context context, final View rootView) {
```
Comment (rubengees) [inline emoji/src/main/java/com/vanniktech/emoji/Utils.java]: @vanniktech I really dislike the "put annotations on the same line" rule, since it leads to awful things like this. Do we really want to enforce that?

**Comment by mario** [comment]
Thanks for the style fixes - I really don't sleep much this year so I must have missed the proper part of the CI output :(

**Comment by rubengees** [comment]
The CI doesn't output the findbugs issues (on which the build failed), which is why I recommend to run the build always locally.

**Comment by mario** [comment]
Less trivial than I though, but I think I got it. @rubengees could you please test?

File: emoji/src/main/java/com/vanniktech/emoji/Utils.java (hunk 11 above)
Comment (vanniktech) [reply emoji/src/main/java/com/vanniktech/emoji/Utils.java]: Yeah we should not enforce it.

**Comment by mario** [comment]
There were two separate leaks that I've hopefully fixed correctly - and hopefully the build turns green this time.

**Comment by mario** [comment]
Tadadadadada .... it's green! :D

**Comment by mario** [comment]
Flow (Assuming we just started)

- Click the emoji toggle button
- Check if the EditText we're using has a noExtractUI flag and we're in a landscape orientation
- If we are, store the original IME options, set the flag on the editText and restart input so the changes would get picked up by the keyboard right away

We do this because the global layout doesn't get into effect with fullscreen EditText since the keyboard is in another process and in a different layout.

We set the receiver to know what happens when we try to show the keyboard, and toggle the keyboard. If a keyboard is already shown, it'll show the Emoji popup.

- Now that we basically have a regular keyboard and views, we can measure keyboard height using two alternatives:

- hidden method to get keyboard height
- magic calculations as a fallback in case reflection fails (even though the fallback also uses reflection to a degree)

- on dismiss, we basically have to do three things:
    - clear the emoji receiver so we don't leak
    - check if we changed the original imeOptions of the editText and if so, restore them
    - cancel autofillManager so we don't leak EmojiSpans

Let me know if I failed to explain something properly and I'll happily do it.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java [hunk 12]
```diff
@@ -229,12 +224,22 @@ public void dismiss() {
...
       final InputMethodManager inputMethodManager = (InputMethodManager) context.getSystemService(Context.INPUT_METHOD_SERVICE);
+
       if (inputMethodManager != null) {
         inputMethodManager.restartInput(editText);
       }
+
+      if (SDK_INT >= O) {
+        AutofillManager autofillManager = context.getSystemService(AutofillManager.class);
+        if (autofillManager != null) {
+          autofillManager.cancel();
```
Comment (rubengees) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: Great! I sometimes saw this leak in my app, but always thought that was an Android SDK one.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiResultReceiver.java [hunk 13]
```diff
@@ -0,0 +1,32 @@
+package com.vanniktech.emoji;
+
+import android.os.Bundle;
+import android.os.Handler;
+import android.os.ResultReceiver;
+
+public class EmojiResultReceiver extends ResultReceiver {
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiResultReceiver.java]:
```suggestion
public final class EmojiResultReceiver extends ResultReceiver {
```

File: emoji/src/main/java/com/vanniktech/emoji/EmojiResultReceiver.java [hunk 14]
```diff
@@ -0,0 +1,32 @@
...
+  private Receiver receiver;
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/EmojiResultReceiver.java]:
```suggestion
  @Nullable private Receiver receiver;
```

File: emoji/src/main/java/com/vanniktech/emoji/Utils.java [hunk 15]
```diff
@@ -50,19 +45,73 @@
...
-  static int getScreenHeight(@NonNull final Activity context) {
-    return dpToPx(context, context.getResources().getConfiguration().screenHeightDp);
+  @SuppressWarnings({"unchecked", "JavaReflectionMemberAccess"}) static int getInputMethodHeight(final Context context, final View rootView) {
+    try {
+      final InputMethodManager imm = (InputMethodManager) context.getApplicationContext().getSystemService(Context.INPUT_METHOD_SERVICE);
+      final Class inputMethodManagerClass = imm.getClass();
+      final Method visibleHeightMethod = inputMethodManagerClass.getDeclaredMethod("getInputMethodWindowVisibleHeight");
+      visibleHeightMethod.setAccessible(true);
+      return (int) visibleHeightMethod.invoke(imm);
+    } catch (NoSuchMethodException exception) {
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/Utils.java]: nit: can be grouped together

File: emoji/src/main/java/com/vanniktech/emoji/Utils.java [hunk 16]
```diff
@@ -50,19 +45,73 @@
...
+      attachInfoField.setAccessible(true);
+      final Object attachInfo = attachInfoField.get(rootView);
+      if (attachInfo != null) {
+        final Field stableInsetsField = attachInfo.getClass().getDeclaredField("mStableInsets");
+        stableInsetsField.setAccessible(true);
+        return ((Rect) stableInsetsField.get(attachInfo)).bottom;
+      }
+    } catch (NoSuchFieldException noSuchFieldException) {
+      Log.w(TAG, noSuchFieldException.getLocalizedMessage());
+    } catch (IllegalAccessException illegalAccessException) {
```
Comment (vanniktech) [inline emoji/src/main/java/com/vanniktech/emoji/Utils.java]: same

File: emoji/src/main/java/com/vanniktech/emoji/Utils.java (hunk 15 above)
Comment (rubengees) [reply emoji/src/main/java/com/vanniktech/emoji/Utils.java]: No they can't, tried that and the IDE complained, because this gets compiled to catch an exception only available on Java 8 if I recall correctly. Catching generic `Exception` should also not be done since it hides `RuntimeException`s on which we want to crash.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java (hunk 12 above)
Comment (mario) [reply emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: :) It's almost like magic! :)

**Comment by mario** [comment]
@rubengees can we merge? After that, @vanniktech can make a release.

File: emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java (hunk 12 above)
Comment (mario) [reply emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java]: I'm pretty sure this is the only available open source lib these days that handles keyboard absolutely correctly btw, which is a great accomplishment - thanks to both @rubengees and @vanniktech for pushing when things didn't work as they were supposed to!

**Comment by rubengees** [comment]
I'll make a last test soon, then I'll approve, thanks for the explanation!

**Comment by vanniktech** [comment]
Thanks @mario really appreciate the effort you put into this! Feel free to merge!

**Comment by mario** [comment]
Please make a release now, thanks! :)

**Comment by vanniktech** [comment]
Will do first thing in the morning tomorrow
